name = "Includev"
uuid = "c52c099d-d419-4a1e-a69e-e47d1491ab96"
authors = ["Jacques David <jacques.david@free.fr>"]
version = "0.1.0"

[deps]
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"

[compat]
julia = "^1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
